name: Weekly FPL Data Collection

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight (UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python fpl_data_collector.py

      - name: Save output files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fpl-data
          path: FPL_Data_*/FPL_Data_GW*.csv  # Correct path with season folder

      - name: Commit and push results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Use your PAT secret
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add FPL_Data_*/FPL_Data_GW*.csv  # Add files in the season folder
          git commit -m "Auto-commit GW data"
          git push --quiet "https://$GH_PAT@github.com/Dante777bm/fpl-data-collector.git" main > /dev/null 2>&1
