name: Weekly FPL Data Collection

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil

      - name: Download FPL static data
        run: python FPL JSON.py

      - name: Run data collection script
        run: python fpl_data_collector.py

      - name: Save output files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fpl-data
          path: FPL_Data_*/FPL_Data_GW*.csv  # Matches season folder + GW files

      - name: Commit and push results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Use your PAT secret
        run: |
          git config --global user.email "bmambwe777@gmail.com"
          git config --global user.name "Bwalya Mambwe"
          git add FPL_Data_*/FPL_Data_GW*.csv  # Add files in the season folder
          git commit -m "Auto-commit GW data for GW${{ github.run_number }}"
          git push --quiet "https://$GH_PAT@github.com/your-username/fpl-data-collector.git" main > /dev/null 2>&1
