name: Weekly FPL Data Collection

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data collection script
        run: python fpl_data_collector.py

      - name: Save output files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fpl-data
          path: FPL_Data_*/FPL_Data_GW*.csv

      - name: Commit and push results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "bmambwe777@gmail.com"
          git config --global user.name "Dante777bm"
          git add FPL_Data_*/FPL_Data_GW*.csv
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-commit latest FPL gameweek data"
            git push https://Dante777bm:${GH_PAT}@github.com/Dante777bm/fpl-data-collector.git main
          fi
