name: Daily FPL Data Collection

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Pull latest changes
        run: git pull

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data collection script
        run: python fpl_data_collector.py

      - name: Run merge script
        run: python merge_gws.py

      - name: Run top 50 players script
        run: python "Top 50 Players.py"

      - name: Run player model script
        run: python fpl_player_model.py

      - name: Save output files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fpl-data
          path: |
            FPL_Data_*/*.csv

      - name: Commit and push results
        run: |
          echo ">>> Running the updated workflow script <<<"
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-commit latest FPL data"
            git push
          fi
